Fix staticcheck warnings
$ staticcheck ./... | fmt -w 80 -s
internal/format/format.go:204:17: error strings should not end with punctuation
or newlines (ST1005)
internal/stream/stream.go:15:2: "golang.org/x/crypto/poly1305" is
deprecated: Poly1305 as implemented by this package is a cryptographic
building block that is not safe for general purpose use. For
encryption, use the full ChaCha20-Poly1305 construction implemented by
golang.org/x/crypto/chacha20poly1305. For authentication, use a general
purpose MAC such as HMAC implemented by crypto/hmac.  (SA1019)
plugin/client.go:385:2: field stderr is unused (U1000)

$ gotip vet ./cmd/...
cmd/age-keygen/keygen.go:161:13: non-constant format string in call to log.Printf